/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.dashboardPanels;

/**
 *
 * @author Chow
 */
public class ParkingLayoutPanel extends javax.swing.JPanel {

    /**
     * Creates new form ParkingLayoutPanel
     */
    public ParkingLayoutPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        parkingFloor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        A1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        A2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        A3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        A4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        A5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        A6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        A7 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        A8 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        A9 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        B4 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        B3 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        B8 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        B6 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        B7 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        B1 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        B9 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        B5 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        B2 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        C8 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        C4 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        C7 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        C1 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        C9 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        C2 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        C3 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        C5 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        C6 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        PWD2 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        PWD3 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        E4 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        E3 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        E1 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        E6 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        E2 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        E5 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        PWD1 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        E8 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        E9 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        E7 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        D1 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        D9 = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        D5 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        D7 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        D6 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        D2 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        D3 = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        D4 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        D8 = new javax.swing.JLabel();
        jPanel59 = new javax.swing.JPanel();
        D11 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        D10 = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        E10 = new javax.swing.JLabel();
        jPanel60 = new javax.swing.JPanel();
        E11 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(144, 238, 144));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 150));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A-01");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(144, 238, 144));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel7.setPreferredSize(new java.awt.Dimension(100, 150));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("A1");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(38, 38, 38))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel8)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(144, 238, 144));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 150));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("A1");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(38, 38, 38))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel10)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(144, 238, 144));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel15.setPreferredSize(new java.awt.Dimension(100, 150));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("A1");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(38, 38, 38))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel16)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(144, 238, 144));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel17.setPreferredSize(new java.awt.Dimension(100, 150));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("A1");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(38, 38, 38))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel18)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        parkingFloor.setBackground(new java.awt.Color(153, 153, 153));
        parkingFloor.setPreferredSize(new java.awt.Dimension(1098, 766));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PARKING LAYOUT");

        jPanel1.setBackground(new java.awt.Color(144, 238, 144));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel1.setLayout(new java.awt.BorderLayout());

        A1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        A1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A1.setText("A1");
        jPanel1.add(A1, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(144, 238, 144));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel5.setLayout(new java.awt.BorderLayout());

        A2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        A2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A2.setText("A2");
        jPanel5.add(A2, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(144, 238, 144));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel6.setLayout(new java.awt.BorderLayout());

        A3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        A3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A3.setText("A3");
        jPanel6.add(A3, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(144, 238, 144));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel8.setLayout(new java.awt.BorderLayout());

        A4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        A4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A4.setText("A4");
        jPanel8.add(A4, java.awt.BorderLayout.CENTER);

        jPanel10.setBackground(new java.awt.Color(144, 238, 144));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel10.setLayout(new java.awt.BorderLayout());

        A5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        A5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A5.setText("A5");
        jPanel10.add(A5, java.awt.BorderLayout.CENTER);

        jPanel11.setBackground(new java.awt.Color(144, 238, 144));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel11.setLayout(new java.awt.BorderLayout());

        A6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        A6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A6.setText("A6");
        jPanel11.add(A6, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(144, 238, 144));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel12.setLayout(new java.awt.BorderLayout());

        A7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        A7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A7.setText("A7");
        jPanel12.add(A7, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(144, 238, 144));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel13.setLayout(new java.awt.BorderLayout());

        A8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        A8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A8.setText("A8");
        jPanel13.add(A8, java.awt.BorderLayout.CENTER);

        jPanel14.setBackground(new java.awt.Color(144, 238, 144));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel14.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("EXIT");
        jPanel14.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanel16.setBackground(new java.awt.Color(144, 238, 144));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel16.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ENTRANCE");
        jPanel16.add(jLabel17, java.awt.BorderLayout.CENTER);

        jPanel18.setBackground(new java.awt.Color(144, 238, 144));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel18.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel18.setLayout(new java.awt.BorderLayout());

        A9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        A9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        A9.setText("A9");
        jPanel18.add(A9, java.awt.BorderLayout.CENTER);

        jPanel22.setBackground(new java.awt.Color(144, 238, 144));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel22.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel22.setLayout(new java.awt.BorderLayout());

        B4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B4.setText("B4");
        jPanel22.add(B4, java.awt.BorderLayout.CENTER);

        jPanel21.setBackground(new java.awt.Color(144, 238, 144));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel21.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel21.setLayout(new java.awt.BorderLayout());

        B3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B3.setText("B3");
        jPanel21.add(B3, java.awt.BorderLayout.CENTER);

        jPanel26.setBackground(new java.awt.Color(144, 238, 144));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel26.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel26.setLayout(new java.awt.BorderLayout());

        B8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B8.setText("B8");
        jPanel26.add(B8, java.awt.BorderLayout.CENTER);

        jPanel24.setBackground(new java.awt.Color(144, 238, 144));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel24.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel24.setLayout(new java.awt.BorderLayout());

        B6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B6.setText("B6");
        jPanel24.add(B6, java.awt.BorderLayout.CENTER);

        jPanel25.setBackground(new java.awt.Color(144, 238, 144));
        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel25.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel25.setLayout(new java.awt.BorderLayout());

        B7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B7.setText("B7");
        jPanel25.add(B7, java.awt.BorderLayout.CENTER);

        jPanel19.setBackground(new java.awt.Color(144, 238, 144));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel19.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel19.setLayout(new java.awt.BorderLayout());

        B1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B1.setText("B1");
        jPanel19.add(B1, java.awt.BorderLayout.CENTER);

        jPanel27.setBackground(new java.awt.Color(144, 238, 144));
        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel27.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel27.setLayout(new java.awt.BorderLayout());

        B9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B9.setText("B9");
        jPanel27.add(B9, java.awt.BorderLayout.CENTER);

        jPanel23.setBackground(new java.awt.Color(144, 238, 144));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel23.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel23.setLayout(new java.awt.BorderLayout());

        B5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B5.setText("B5");
        jPanel23.add(B5, java.awt.BorderLayout.CENTER);

        jPanel20.setBackground(new java.awt.Color(144, 238, 144));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel20.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel20.setLayout(new java.awt.BorderLayout());

        B2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        B2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B2.setText("B2");
        jPanel20.add(B2, java.awt.BorderLayout.CENTER);

        jPanel35.setBackground(new java.awt.Color(144, 238, 144));
        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel35.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel35.setLayout(new java.awt.BorderLayout());

        C8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        C8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C8.setText("C8");
        jPanel35.add(C8, java.awt.BorderLayout.CENTER);

        jPanel31.setBackground(new java.awt.Color(144, 238, 144));
        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel31.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel31.setLayout(new java.awt.BorderLayout());

        C4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        C4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C4.setText("C4");
        jPanel31.add(C4, java.awt.BorderLayout.CENTER);

        jPanel34.setBackground(new java.awt.Color(144, 238, 144));
        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel34.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel34.setLayout(new java.awt.BorderLayout());

        C7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        C7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C7.setText("C7");
        jPanel34.add(C7, java.awt.BorderLayout.CENTER);

        jPanel28.setBackground(new java.awt.Color(144, 238, 144));
        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel28.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel28.setLayout(new java.awt.BorderLayout());

        C1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C1.setText("C1");
        jPanel28.add(C1, java.awt.BorderLayout.CENTER);

        jPanel36.setBackground(new java.awt.Color(144, 238, 144));
        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel36.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel36.setLayout(new java.awt.BorderLayout());

        C9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        C9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C9.setText("C9");
        jPanel36.add(C9, java.awt.BorderLayout.CENTER);

        jPanel29.setBackground(new java.awt.Color(144, 238, 144));
        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel29.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel29.setLayout(new java.awt.BorderLayout());

        C2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C2.setText("C2");
        jPanel29.add(C2, java.awt.BorderLayout.CENTER);

        jPanel30.setBackground(new java.awt.Color(144, 238, 144));
        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel30.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel30.setLayout(new java.awt.BorderLayout());

        C3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C3.setText("C3");
        jPanel30.add(C3, java.awt.BorderLayout.CENTER);

        jPanel32.setBackground(new java.awt.Color(144, 238, 144));
        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel32.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel32.setLayout(new java.awt.BorderLayout());

        C5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        C5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C5.setText("C5");
        jPanel32.add(C5, java.awt.BorderLayout.CENTER);

        jPanel33.setBackground(new java.awt.Color(144, 238, 144));
        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel33.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel33.setLayout(new java.awt.BorderLayout());

        C6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        C6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        C6.setText("C6");
        jPanel33.add(C6, java.awt.BorderLayout.CENTER);

        jPanel38.setBackground(new java.awt.Color(144, 238, 144));
        jPanel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel38.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel38.setLayout(new java.awt.BorderLayout());

        PWD2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PWD2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PWD2.setText("PWD2");
        jPanel38.add(PWD2, java.awt.BorderLayout.CENTER);

        jPanel37.setBackground(new java.awt.Color(144, 238, 144));
        jPanel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel37.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel37.setLayout(new java.awt.BorderLayout());

        PWD3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PWD3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PWD3.setText("PWD3");
        jPanel37.add(PWD3, java.awt.BorderLayout.CENTER);

        jPanel42.setBackground(new java.awt.Color(144, 238, 144));
        jPanel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel42.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel42.setLayout(new java.awt.BorderLayout());

        E4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E4.setText("E4");
        jPanel42.add(E4, java.awt.BorderLayout.CENTER);

        jPanel43.setBackground(new java.awt.Color(144, 238, 144));
        jPanel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel43.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel43.setLayout(new java.awt.BorderLayout());

        E3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E3.setText("E3");
        jPanel43.add(E3, java.awt.BorderLayout.CENTER);

        jPanel45.setBackground(new java.awt.Color(144, 238, 144));
        jPanel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel45.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel45.setLayout(new java.awt.BorderLayout());

        E1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E1.setText("E1");
        jPanel45.add(E1, java.awt.BorderLayout.CENTER);

        jPanel40.setBackground(new java.awt.Color(144, 238, 144));
        jPanel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel40.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel40.setLayout(new java.awt.BorderLayout());

        E6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E6.setText("E6");
        jPanel40.add(E6, java.awt.BorderLayout.CENTER);

        jPanel44.setBackground(new java.awt.Color(144, 238, 144));
        jPanel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel44.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel44.setLayout(new java.awt.BorderLayout());

        E2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E2.setText("E2");
        jPanel44.add(E2, java.awt.BorderLayout.CENTER);

        jPanel41.setBackground(new java.awt.Color(144, 238, 144));
        jPanel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel41.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel41.setLayout(new java.awt.BorderLayout());

        E5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E5.setText("E5");
        jPanel41.add(E5, java.awt.BorderLayout.CENTER);

        jPanel39.setBackground(new java.awt.Color(144, 238, 144));
        jPanel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel39.setPreferredSize(new java.awt.Dimension(100, 150));
        jPanel39.setLayout(new java.awt.BorderLayout());

        PWD1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PWD1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PWD1.setText("PWD1");
        jPanel39.add(PWD1, java.awt.BorderLayout.CENTER);

        jPanel47.setBackground(new java.awt.Color(144, 238, 144));
        jPanel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel47.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel47.setLayout(new java.awt.BorderLayout());

        E8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E8.setText("E8");
        jPanel47.add(E8, java.awt.BorderLayout.CENTER);

        jPanel48.setBackground(new java.awt.Color(144, 238, 144));
        jPanel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel48.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel48.setLayout(new java.awt.BorderLayout());

        E9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E9.setText("E9");
        jPanel48.add(E9, java.awt.BorderLayout.CENTER);

        jPanel46.setBackground(new java.awt.Color(144, 238, 144));
        jPanel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel46.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel46.setLayout(new java.awt.BorderLayout());

        E7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E7.setText("E7");
        jPanel46.add(E7, java.awt.BorderLayout.CENTER);

        jPanel49.setBackground(new java.awt.Color(144, 238, 144));
        jPanel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel49.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel49.setLayout(new java.awt.BorderLayout());

        D1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D1.setText("D1");
        jPanel49.add(D1, java.awt.BorderLayout.CENTER);

        jPanel57.setBackground(new java.awt.Color(144, 238, 144));
        jPanel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel57.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel57.setLayout(new java.awt.BorderLayout());

        D9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D9.setText("D9");
        jPanel57.add(D9, java.awt.BorderLayout.CENTER);

        jPanel53.setBackground(new java.awt.Color(144, 238, 144));
        jPanel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel53.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel53.setLayout(new java.awt.BorderLayout());

        D5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D5.setText("D5");
        jPanel53.add(D5, java.awt.BorderLayout.CENTER);

        jPanel55.setBackground(new java.awt.Color(144, 238, 144));
        jPanel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel55.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel55.setLayout(new java.awt.BorderLayout());

        D7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D7.setText("D7");
        jPanel55.add(D7, java.awt.BorderLayout.CENTER);

        jPanel54.setBackground(new java.awt.Color(144, 238, 144));
        jPanel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel54.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel54.setLayout(new java.awt.BorderLayout());

        D6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D6.setText("D6");
        jPanel54.add(D6, java.awt.BorderLayout.CENTER);

        jPanel50.setBackground(new java.awt.Color(144, 238, 144));
        jPanel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel50.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel50.setLayout(new java.awt.BorderLayout());

        D2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D2.setText("D2");
        jPanel50.add(D2, java.awt.BorderLayout.CENTER);

        jPanel51.setBackground(new java.awt.Color(144, 238, 144));
        jPanel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel51.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel51.setLayout(new java.awt.BorderLayout());

        D3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D3.setText("D3");
        jPanel51.add(D3, java.awt.BorderLayout.CENTER);

        jPanel52.setBackground(new java.awt.Color(144, 238, 144));
        jPanel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel52.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel52.setLayout(new java.awt.BorderLayout());

        D4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D4.setText("D4");
        jPanel52.add(D4, java.awt.BorderLayout.CENTER);

        jPanel56.setBackground(new java.awt.Color(144, 238, 144));
        jPanel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel56.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel56.setLayout(new java.awt.BorderLayout());

        D8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D8.setText("D8");
        jPanel56.add(D8, java.awt.BorderLayout.CENTER);

        jPanel59.setBackground(new java.awt.Color(144, 238, 144));
        jPanel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel59.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel59.setLayout(new java.awt.BorderLayout());

        D11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D11.setText("D11");
        jPanel59.add(D11, java.awt.BorderLayout.CENTER);

        jPanel58.setBackground(new java.awt.Color(144, 238, 144));
        jPanel58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel58.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel58.setLayout(new java.awt.BorderLayout());

        D10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        D10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D10.setText("D10");
        jPanel58.add(D10, java.awt.BorderLayout.CENTER);

        jPanel61.setBackground(new java.awt.Color(144, 238, 144));
        jPanel61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel61.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel61.setLayout(new java.awt.BorderLayout());

        E10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E10.setText("E10");
        jPanel61.add(E10, java.awt.BorderLayout.CENTER);

        jPanel60.setBackground(new java.awt.Color(144, 238, 144));
        jPanel60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel60.setPreferredSize(new java.awt.Dimension(50, 75));
        jPanel60.setLayout(new java.awt.BorderLayout());

        E11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        E11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        E11.setText("E11");
        jPanel60.add(E11, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout parkingFloorLayout = new javax.swing.GroupLayout(parkingFloor);
        parkingFloor.setLayout(parkingFloorLayout);
        parkingFloorLayout.setHorizontalGroup(
            parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parkingFloorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parkingFloorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(382, 382, 382)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(parkingFloorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parkingFloorLayout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(parkingFloorLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parkingFloorLayout.createSequentialGroup()
                        .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(parkingFloorLayout.createSequentialGroup()
                        .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(parkingFloorLayout.createSequentialGroup()
                                .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(parkingFloorLayout.createSequentialGroup()
                                .addComponent(jPanel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(192, 192, 192))
        );
        parkingFloorLayout.setVerticalGroup(
            parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkingFloorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parkingFloorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parkingFloorLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parkingFloorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(parkingFloorLayout.createSequentialGroup()
                                .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel53, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(parkingFloorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parkingFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parkingFloor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel A9;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel B7;
    private javax.swing.JLabel B8;
    private javax.swing.JLabel B9;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel C3;
    private javax.swing.JLabel C4;
    private javax.swing.JLabel C5;
    private javax.swing.JLabel C6;
    private javax.swing.JLabel C7;
    private javax.swing.JLabel C8;
    private javax.swing.JLabel C9;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D10;
    private javax.swing.JLabel D11;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D3;
    private javax.swing.JLabel D4;
    private javax.swing.JLabel D5;
    private javax.swing.JLabel D6;
    private javax.swing.JLabel D7;
    private javax.swing.JLabel D8;
    private javax.swing.JLabel D9;
    private javax.swing.JLabel E1;
    private javax.swing.JLabel E10;
    private javax.swing.JLabel E11;
    private javax.swing.JLabel E2;
    private javax.swing.JLabel E3;
    private javax.swing.JLabel E4;
    private javax.swing.JLabel E5;
    private javax.swing.JLabel E6;
    private javax.swing.JLabel E7;
    private javax.swing.JLabel E8;
    private javax.swing.JLabel E9;
    private javax.swing.JLabel PWD1;
    private javax.swing.JLabel PWD2;
    private javax.swing.JLabel PWD3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel parkingFloor;
    // End of variables declaration//GEN-END:variables
}
